# Path to oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Export path to root of dotfiles repo
export DOTFILES=${DOTFILES:-"$HOME/Dotfiles"}

# Locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# tmux's plugin settings
export TERM="xterm-256color"
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOCONNECT=false

# OH MY ZSH
# == == ===

# Use oh-my-zsh spaceship's custom theme
ZSH_THEME="spaceship"

# Use case-sensitive completion.
# CASE_SENSITIVE="true"

# Use hyphen-insensitive completion.
# Note: Case sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Disable colors in ls.
# DISABLE_LS_COLORS="true"

# Disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Enable command auto-correction.
# ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Disable marking untracked files under VCS as dirty.
# This makes repository status check for large repositories much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Change the command execution time stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Custom folder than $ZSH/custom
#ZSH_CUSTOM="$DOTFILES/zsh"

# Specify which oh-my-zsh plugins to use
plugins=(
  git
  tmux
  kubectl
  aws
  brew
  cargo
  cp
  docker
  docker-compose
  emoji
  encode64
  go
  golang
  helm
  kops
  mvn
  minikube
  nmap
  npm
  node
  postgres
  rsync
  ssh-agent
  terraform
)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Source tmux's configuration
tmux source ~/.tmux.conf

# Load extra (private) settings
[ -f ~/.zshlocal ] && source ~/.zshlocal
